Repository Codemao-Python-Rules-Commissions/policy-work-team, pull requests merged in 2023-08, with the labels that each got.

#4 Add More Policy
  .github/policies/AdminTrigger.yml
  .github/policies/automergeTriggers.yml
  .github/workflows/Pull.yml
  .github/workflows/sync.yml
  Policy/Python代码临时管理规定(试行).md
  Policy/README.md
  Policy/广告管理条例.md
  Policy/成员移除名单.md
  Policy/群规制定条例.md
  README.md
Labels: Merge-Needed, Policy-Request, Policy-Modify, Review-Needed, Breaking-Change

#5 Make Two Members
  .github/workflows/Pull.yml
  Policy/群规制定条例.md
  README.md
Labels: Member-Approved, Policy-Accepted, Policy-Modify, Member-Adding, Project-File

#8 feat: change 字 to 字符, add 2 rules
  Policy/广告管理条例.md
Labels: Administrator-Approved, Policy-Modify, Review-Needed

#9 Add 成员工作流程.md
  docs/成员工作流程.md
Labels: Member-Approved, Review-Needed, Project-File, Commissions

#10 add liulyxandy-codemao
  README.md
Labels: documentation, Policy-Accepted, Member-Adding, Project-File, Commissions

#13 Make liulyxandy-codemao Co-Admin & Make QiKeZhiCao Member
  README.md
Labels: Merge-Needed, Review-Needed, Member-Adding, Project-File, Announcement, Commissions, Commissions-Member

#14 Create Auto-Assign.yml
  .github/workflows/Auto-Assign.yml
Labels: Project-File

#15 Command-Execute: Remove 天边的生活
  Policy/成员移除名单.md
Labels: Administrator-Approved, Merge-Needed, Policy-Modify, Command-Execute

#17 Create 公告20230815.md
  公告20230815.md
Labels: Administrator-Approved, Policy-Request, Review-Needed
